In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from dmba import classificationSummary
import numpy as np


In [10]:
#create a data frame of data provided
card_df = pd.DataFrame({
    'Years': [4, 18, 1, 3, 15, 6],
    'Salary':[43, 65, 53, 95, 88, 112],
    'Used_credit':[0, 1, 0, 0, 1, 1],
})


In [11]:
predictors_df = card_df.drop(columns=['Used_credit'])
response_df = card_df.Used_credit

X = np.array(predictors_df)
y = np.array(response_df)
print(card_df)
print(response_df)
print(X), print(y)

   Years  Salary  Used_credit
0      4      43            0
1     18      65            1
2      1      53            0
3      3      95            0
4     15      88            1
5      6     112            1
0    0
1    1
2    0
3    0
4    1
5    1
Name: Used_credit, dtype: int64
[[  4  43]
 [ 18  65]
 [  1  53]
 [  3  95]
 [ 15  88]
 [  6 112]]
[0 1 0 0 1 1]


(None, None)

In [18]:
# Multi-layer Perceptron classifier
clf = MLPClassifier(hidden_layer_sizes=(3), activation='logistic', solver='lbfgs', random_state=1)
clf.fit(X, y)

#Network Structure

for i, (weights, intercepts) in enumerate(zip(clf.coefs_, clf.intercepts_)):
    print('Hidden layer' if i == 0 else 'Output layer', '{0[0]} => {0[1]}' .format(weights.shape))
    print(' Intercepts:\n ', intercepts)
    print(' Weights: ')
    for weight in weights:
        print(' ', weight)
    print() 

Hidden layer 2 => 3
 Intercepts:
  [-0.39685328 -0.19535194 -0.13057996]
 Weights: 
  [-0.10494688  0.27865319 -0.63222532]
  [-0.2500133  -0.44676191 -0.51558567]

Output layer 3 => 1
 Intercepts:
  [2.33295553e-05]
 Weights: 
  [0.05488134]
  [-0.11426076]
  [0.2619045]



In [19]:
# Predictions
print(pd.concat([
    card_df,
    pd.DataFrame(clf.predict_proba(X), columns=[0, 1])
], axis=1))

   Years  Salary  Used_credit         0         1
0      4      43            0  0.499994  0.500006
1     18      65            1  0.499994  0.500006
2      1      53            0  0.499994  0.500006
3      3      95            0  0.499994  0.500006
4     15      88            1  0.499994  0.500006
5      6     112            1  0.499994  0.500006
